name: 'Local Test'
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Run Local Action'
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          resource-pack-path: './test-data/creeper_pack'
